#!/bin/sh

# work in progress script to install dotfiles

mv .git ../ || err "Not enough perms to install dots"

current=$PWD
last=$(find $current) 

err() {
	printf 'ERROR: %s\n' $1
	exit 1
}

for i in $last; do
	if [ ! -d $i -a $i != "$current/installdots" -a $i != "$current/README" -a $i != "$current/setup" ]
	then
		file="$(echo $i | sed "s|$current|$HOME|g")"
		directory="$(dirname $file)"
		mkdir -p $directory
		ln -sf $i $file
	fi
done

mv ../.git ./
