#!/bin/sh

# Setup personal dotfiles/system
# DEPENDENCIES (git, mkdir with --parent option, ln, touch)
current=$(pwd)
confighome=${XDG_CONFIG_HOME:-$HOME/.config}
datahome=${XDG_CONFIG_HOME:-$HOME/.local/share}
cachehome=${XDG_CACHE_HOME:-$HOME/.cache}
templatesdir=${XDG_TEMPLATES_DIR:-$HOME/Templates}
localbin="$HOME/.local/bin"
remotegiturl="git@usernamesystems.xyz"
remotepubgitdir="/var/www/git"

# XDG TEMPLATES DIRECTORY
[ ! -d $templatesdir ] && mkdir -p $templatesdir

[ -d $templatesdir/snippets ] && rm -rf $templatesdir/snippets
[ -d $templatesdir/licenses ] && rm -rf $templatesdir/licenses
ln -sf $current/Templates/licenses $templatesdir/licenses
ln -sf $current/Templates/snippets $templatesdir/snippets

# SETUP SCRIPTS DIR
[ ! -d $localbin ] && mkdir -p $localbin
cd $localbin && git clone $remotegiturl:$remotepubgitdir/bin ./ || echo "Seems like $localbin has already been setup"
cd $current

# DOTFILES
mkdir -p $confighome

# history file
mkdir -p $cachehome/bash

ln -sf $current/.bashrc $HOME/.bashrc

mkdir -p $HOME/.vim 
ln -sf $current/.vim/vimrc $HOME/.vim/vimrc

mkdir -p $confighome/dwm
ln -sf $current/.config/dwm/autostart.sh $confighome/dwm/autostart.sh

mkdir -p $confighome/git
ln -sf $current/.config/git/config $confighome/git/config

mkdir -p $confighome/gtk-2.0
ln -sf $current/.config/gtk-2.0/gtkrc $confighome/gtk-2.0/gtkrc

mkdir -p $confighome/gtk-3.0
ln -sf $current/.config/gtk-3.0/settings.ini $confighome/gtk-3.0/settings.ini

mkdir -p $confighome/lynx
ln -sf $current/.config/lynx/lynx.lss $confighome/lynx/lynx.lss

mkdir -p $confighome/mpv
ln -sf $current/.config/mpv/input.conf $confighome/mpv/input.conf
ln -sf $current/.config/mpv/mpv.conf $confighome/mpv/mpv.conf

mkdir -p $confighome/openbox
ln -sf $current/.config/openbox/autostart $confighome/openbox/autostart
ln -sf $current/.config/openbox/rc.xml $confighome/openbox/rc.xml
ln -sf $current/.config/openbox/menu.xml $confighome/openbox/menu.xml

mkdir -p $confighome/picom
ln -sf $current/.config/picom/picom.conf $confighome/picom/picom.conf

mkdir -p $confighome/shell
ln -sf $current/.config/shell/aliasrc $confighome/shell/aliasrc
ln -sf $current/.config/shell/profile $confighome/shell/profile
# for different environments, may require different envvars set
touch $confighome/shell/machinerc 

mkdir -p $confighome/sxhkd
ln -sf $current/.config/sxhkd/sxhkdrc $confighome/sxhkd/sxhkdrc

mkdir -p $confighome/tint2
ln -sf $current/.config/tint2/tint2rc $confighome/tint2/tint2rc

mkdir -p $confighome/x11
ln -sf $current/.config/x11/.xinitrc $confighome/x11/.xinitrc
ln -sf $current/.config/x11/.Xresources $confighome/x11/.Xresources

mkdir -p $datahome/icons/default
ln -sf $current/.local/share/icons/default/index.theme $datahome/icons/default/index.theme
