#!/bin/sh

# Setup personal dotfiles/system
# DEPENDENCIES (git, mkdir with --parent option, ln, touch)

current=$PWD
confighome=${XDG_CONFIG_HOME:-$HOME/.config}
datahome=${XDG_CONFIG_HOME:-$HOME/.local/share}
cachehome=${XDG_CACHE_HOME:-$HOME/.cache}

documentsdir=${XDG_DOCUMENTS_DIR:-$HOME/Documents}
downloadsdir=${XDG_DOWNLOADS_DIR:-$HOME/Downloads}
musicdir=${XDG_PICTURES_DIR:-$HOME/Music}
publicdir=${XDG_PUBLIC_DIR:-$HOME/Public}
picturesdir=${XDG_PICTURES_DIR:-$HOME/Pictures}
templatesdir=${XDG_TEMPLATES_DIR:-$HOME/Templates}
videosdir=${XDG_PICTURES_DIR:-$HOME/Videos}
reposdir=${REPOS_DIR:-$HOME/repos}
gamesdir=${GAMES_DIR:-$HOME/Games}
applicationsdir=${APPLICATIONS_DIR:-$HOME/Applications}

localbin="$HOME/.local/bin"
remotegiturl="git@usernamesystems.xyz"
remoteprivgitdir="privaterepos"
remotepubgitdir="/var/www/git"

#
# XDG TEMPLATES DIRECTORY
#
[ ! -d $templatesdir ] && mkdir -p $templatesdir

[ -d $templatesdir/snippets ] && rm -rf $templatesdir/snippets
[ -d $templatesdir/licenses ] && rm -rf $templatesdir/licenses
ln -sf $current/Templates/licenses $templatesdir/licenses
ln -sf $current/Templates/snippets $templatesdir/snippets

#
# SETUP DOCUMENTS/NOTES DIR
#
git clone $remotegiturl:$remoteprivgitdir/notes $documentsdir/notes/ || \
	echo "Seems like $documentsdir/notes has already been setup"

#
# SETUP SCRIPTS DIR
#
[ ! -d $localbin ] && mkdir -p $localbin
git clone $remotegiturl:$remotepubgitdir/bin $localbin || \
	echo "Seems like $localbin has already been setup"

#
# DOTFILES
#
mkdir -p $confighome

# history file
mkdir -p $cachehome/bash

ln -sf $current/.bashrc $HOME/.bashrc

ln -sf $current/.profile $HOME/.profile

mkdir -p $HOME/.vim
ln -sf $current/.vim/vimrc $HOME/.vim/vimrc
# install vim plugins in .vim/setuppackages
$current/.vim/setuppackages
ln -sf $current/.vim/setuppackages $HOME/.vim/setuppackages

mkdir -p $confighome/alacritty
ln -sf $current/.config/alacritty/alacritty.yml \
  	$confighome/alacritty/alacritty.yml

mkdir -p $confighome/dwm
ln -sf $current/.config/dwm/autostart.sh $confighome/dwm/autostart.sh

mkdir -p $confighome/fontconfig
ln -sf $current/.config/fontconfig/fonts.conf $confighome/fontconfig/fonts.conf
ln -sf $current/.config/fontconfig/backup.conf $confighome/fontconfig/backup.conf

mkdir -p $confighome/foot
ln -sf $current/.config/foot/foot.ini $confighome/foot/foot.ini

mkdir -p $confighome/git
ln -sf $current/.config/git/config $confighome/git/config

mkdir -p $confighome/gtk-2.0
ln -sf $current/.config/gtk-2.0/gtkrc $confighome/gtk-2.0/gtkrc

mkdir -p $confighome/gtk-3.0
ln -sf $current/.config/gtk-3.0/settings.ini $confighome/gtk-3.0/settings.ini

mkdir -p $confighome/lynx
ln -sf $current/.config/lynx/lynx.lss $confighome/lynx/lynx.lss

mkdir -p $confighome/mpv
ln -sf $current/.config/mpv/input.conf $confighome/mpv/input.conf
ln -sf $current/.config/mpv/mpv.conf $confighome/mpv/mpv.conf

mkdir -p $confighome/openbox
ln -sf $current/.config/openbox/autostart $confighome/openbox/autostart
ln -sf $current/.config/openbox/rc.xml $confighome/openbox/rc.xml
ln -sf $current/.config/openbox/menu.xml $confighome/openbox/menu.xml

mkdir -p $confighome/picom
ln -sf $current/.config/picom/picom.conf $confighome/picom/picom.conf

mkdir -p $confighome/sfeed
ln -sf $current/.config/sfeed/sfeedrc $confighome/sfeed/sfeedrc

mkdir -p $confighome/shell
ln -sf $current/.config/shell/aliasrc $confighome/shell/aliasrc
ln -sf $current/.config/shell/profile $confighome/shell/profile
ln -sf $current/.config/shell/prompt $confighome/shell/prompt
# for different environments, may require different envvars set
touch $confighome/shell/machinerc

mkdir -p $confighome/status
ln -sf $current/.config/status/getmem $confighome/status/getmem
ln -sf $current/.config/status/getvol $confighome/status/getvol
ln -sf $current/.config/status/getping $confighome/status/getping
ln -sf $current/.config/status/getdt $confighome/status/getdt
ln -sf $current/.config/status/getbat $confighome/status/getbat

mkdir -p $confighome/sway
ln -sf $current/.config/sway/config $confighome/sway/config
ln -sf $current/.config/sway/statusbar $confighome/sway/statusbar

mkdir -p $confighome/sxhkd
ln -sf $current/.config/sxhkd/sxhkdrc $confighome/sxhkd/sxhkdrc

mkdir -p $confighome/tint2
ln -sf $current/.config/tint2/tint2rc $confighome/tint2/tint2rc

mkdir -p $confighome/tmux
ln -sf $current/.config/tmux/tmux.conf $confighome/tmux/tmux.conf

mkdir -p $confighome/waybar
ln -sf $current/.config/waybar/config $confighome/waybar/config
ln -sf $current/.config/waybar/style.css $confighome/waybar/style.css

mkdir -p $confighome/x11
ln -sf $current/.config/x11/.xinitrc $confighome/x11/.xinitrc
ln -sf $current/.config/x11/.Xresources $confighome/x11/.Xresources

mkdir -p $datahome/icons/default
ln -sf $current/.local/share/icons/default/index.theme $datahome/icons/default/index.theme
