#!/bin/sh

# Requires ~/.local/bin/vimpkg to be in PATH

vimpkg i morhetz/gruvbox
vimpkg i mhinz/vim-startify
vimpkg i pacha/vem-tabline
vimpkg i preservim/nerdtree
vimpkg i junegunn/goyo.vim
vimpkg i junegunn/limelight.vim
#vimpkg i ryanoasis/vim-devicons
