#!/bin/sh

# Requires ~/.local/bin/vimpkg to be in PATH

com="$HOME/.local/bin/vimpkg"

$com i morhetz/gruvbox
$com i tpope/vim-markdown
$com i mhinz/vim-startify
$com i pacha/vem-tabline
#$com i preservim/nerdtree
$com i junegunn/goyo.vim
$com i junegunn/limelight.vim
#$com i ryanoasis/vim-devicons
