# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false
format = '''
[┌──>](bold blue) $directory$package$git_branch$git_status[<──](bold blue)
[└\$](bold blue) '''

[directory]
style = 'bold yellow'

[git_branch]
style = 'bold purple'

