" Jesse's vim configuration
" vim: et ts=2 sts=-1 sw=0

""""""""""""""""
""" Vim defaults
""""""""""""""""
""" - Check out <https://github.com/liuchengxu/vim-better-default>
scriptencoding utf-8
set nocompatible
syntax on                      " Syntax highlighting
filetype plugin indent on      " Automatically detect file types

set encoding=utf-8             " Set default encoding
set termencoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936
set fileformats=unix,dos,mac   " Use Unix as the standard file type

" Better clipboard functionality
set clipboard=unnamedplus

set background=dark            " Assume dark background
set autoindent                 " Indent at the same level of the previous line
set autoread                   " Automatically read a file changed outside of vim
set complete-=i                " Exclude files completion
set display=lastline           " Show as much as possible of the last line
set history=10000              " Maximum history record
set hlsearch                   " Highlight search terms
set incsearch                  " Find as you type search
set laststatus=2               " Always show status line
set mouse=a                    " Automatically enable mouse usage
set smarttab                   " Smart tab
set ttyfast                    " Faster redrawing
set ttymouse=xterm2
set viminfo+=!                 " Viminfo include !
set wildmenu                   " Show list instead of just completing

set shortmess=atOI             " No help Uganda information, and overwrite read messages to avoid PRESS ENTER prompts
set ignorecase                 " Case insensitive search
set smartcase                  " ... but case sensitive when uc present
set scrolloff=3                " Minimum lines to keep above and below cursor
set linebreak
set wrap                       " Wrap long lines
set splitright                 " Puts new vsplit windows to the right of the current
set splitbelow                 " Puts new split windows to the bottom of the current
set autowrite                  " Automatically write a file when leaving a modified buffer
set mousehide                  " Hide the mouse cursor while typing
set hidden                     " Allow buffer switching without saving
set t_Co=256                   " Use 256 colors
set ruler                      " Show the ruler
set showcmd                    " Show partial commands in status line and Selected characters/lines in visual mode
set showmode                   " Show current mode in command-line
set showmatch                  " Show matching brackets/parentthesis
set matchtime=5                " Show matching time
set report=0                   " Always report changed lines
set linespace=0                " No extra spaces between rows
set pumheight=20               " Avoid the pop up menu occupying the whole screen
set whichwrap+=<,>,h,l         " Allow backspace and cursor keys to cross line boundaries

set wildignore+=*swp,*.class,*.pyc,*.png,*.jpg,*.gif,*.zip
set wildignore+=*/tmp/*,*.o,*.obj,*.so     " Unix
set wildignore+=*\\tmp\\*,*.exe            " Windows

" indent functionality
set tabstop=4      " An indentation every four columns
set shiftwidth=0   " Always equal to tabstop
set softtabstop=-1 " Let backspace delete indent (always equal to shiftwidth)
"set expandtab     " Expand tab into spaces

set t_ut= " http://stackoverflow.com/questions/6427650/vim-in-tmux-background-color-changes-when-paging/15095377#15095377

" Annoying temporary files
set directory=/tmp//,.
set backupdir=/tmp//,.
if v:version >= 703
  set undodir=/tmp//,.
endif

highlight clear SignColumn  " SignColumn should match background

if v:version >= 800
  " stop vim from silently messing with files that it shouldn't
  set nofixendofline

  " better ascii friendly listchars
  set listchars=space:*,trail:*,nbsp:*,extends:>,precedes:<,tab:\|>

  " i hate automatic folding
  set foldmethod=manual
  set nofoldenable
endif 

"""""""""""""""
""" Keybindings
"""""""""""""""

" Set <leader> as space
let mapleader = " "
let g:mapleader = " "

" Visual shifting (does not exit Visual mode)
vnoremap < <gv
vnoremap > >gv

nnoremap <Leader>e :Lex 30<CR>

nnoremap <Leader>d <C-d>
nnoremap <Leader>u <C-u>

nnoremap <C-j> <C-W>j
nnoremap <C-k> <C-W>k
nnoremap <C-h> <C-W>h
nnoremap <C-l> <C-W>l

"""""""""""
""" Plugins
"""""""""""

" only load plugins if vim-plug detected
if filereadable(expand("~/.vim/autoload/plug.vim"))
  call plug#begin('~/.local/share/vim/plugins')
    Plug 'morhetz/gruvbox'
    Plug 'jasonccox/vim-wayland-clipboard'
  call plug#end()

  colorscheme gruvbox
endif 

""" Viminfo
if !has('nvim') | set viminfofile=$XDG_STATE_HOME/vim/viminfo | endif
