require "user.plugins"
require "user.options" 
require "user.keymaps"
require "user.filetypes"

require "user.alpha"
require "user.nvimtree"
require "user.telescope"
require "user.gitsigns"
require "user.bufferline"
require "user.lualine"
require "user.project"
